### ISSUE TITLE
After looting a numbered chest but failing the scenario, should the scenario be marked looted?

### ISSUE THREAD

**Issue by tsmigiel** [teamducro/gloomhaven-storyline#117]
We played scenario 31. We were able to loot the 1 treasure chest, which is not a goal chest, but we did not complete the scenario. I was able to mark the check box next to the treasure in the scenario UI. I was expecting to see the scenario marked as "looted", but I guess it depends on the intention of what "looted" is supposed to mean.

(This also makes me wonder if it is relevant to add a "failed" state for a scenario. Or even how many times a scenario was played.)

I don't have any opinion about what the right thing to do is. I was just surprised the scenario wasn't marked as looted after checking the treasure box.

**Comment by dducro** [comment]
Hey, thanks!

I have a missed treasures filter, these are completed scenarios with unchecked treasures.
Similar to it I added the looted checkmark, so completed scenarios with checked treasures.

However, I removed the completed check with the newest update, because you keep the treasure contents after failing a scenario, thus the scenario is actually looted.

**Comment by dducro** [comment]
About the failed scenario state.
In my opinion this doesn't add much value to the overall storyline, and unfortunately will take valuable screen real estate on mobile.
But If you'd like to track the number of attempts, the paid version has a notes section in the scenario view! Here you may include any info you'd like.
(unfortunately due to technical reasons not available in the free version)

**Comment by tsmigiel** [comment]
Makes sense.
Thanks for all of your work on this project. I love it. I have already paid for 2 campaigns.
Not sure the right place to ask this, but I am wondering what additional features you are planning to add?
I would love to see continued improvements to the card events. Like automatically adding cards for retired and new characters, etc. 
I would also love a way to keep track of characters in a party. Specifically, xp, gold, and which items each have purchased.
Would it be a good idea for me to create a couple of enhancement requests? With more context.

**Comment by dducro** [comment]
Thanks for your support!

I'd like to add player sheets! However, this is a quite big feature and I also want to work on JotL and Frosthaven support.
Solo scenarios are also planned for the near future.
And I also have work on maintaining and updating components of the app to keep it stable on modern devices! :)

Personally I also like the card event tracking and drawing. Automatically adding cards for new characters is easy to implement, but to add them at retirement, I would like to have a player sheet to select when the character retires. Beside that, there are many moments when event cards are added or removed, based on who is playing in the current party and outside the storyline. I think it's confusing if in one case the cards are added automatically and in others the user needs to manually add them. That's why I chose the manual approach for now. This may change in the future, who knows ;)

Feature requests are always welcome.
