### ISSUE TITLE
Add Solo scenarios and Items

### ISSUE THREAD

**Issue by dducro** [teamducro/gloomhaven-storyline#153]

**Comment by dducro** [comment]
Planned for upcoming update!

**Comment by jgwehr** [comment]
This is an awesome new feature (worth promoting on reddit!).

I noticed a very minor bug when I was toggling **between character sheets**
![hZvAHsmqap](https://user-images.githubusercontent.com/13216529/157955523-a12fcba8-b671-49c9-9404-8a5bb67e79f0.gif)

### Steps to Reproduce:
1. Navigate to the Characters tab. _Observed_: the correct icon for this Class appears next to the name of the Classes' solo scenario
3. Navigate to any other character.  _Observed_: the correct icon for this Class appears next to the name of the Classes' solo scenario
4. Navigate back to your first character. _Observed_: the icon for the previous Class appears instead of the current Class.

The icon can be "reset" by navigating to a different tab, such as Party Sheet or Items

**Comment by dducro** [comment]
Thanks, will be fixed! :)
