### ISSUE TITLE
Crimson Scales Pages

### ISSUE THREAD

**Issue by dducro** [teamducro/gloomhaven-storyline#223]
Reported by S.

It looks like the "Pages" for Crimson Scales scenarios are pulling the first page from the Section Book and the second page from the Add-On Scenario Book, which results in displaying sections from different scenarios and then unrelated stuff from the add-ons (this is the case with at least the first two scenarios, I didn't go farther since I don't want to spoil too much for myself). It should be pulling the first listed page from the Rule Book and Scenario Guide, and the second listed page from the Section Book.

**Comment by jgwehr** [comment]
I noticed this for scenario 13 while looking at another Issue.
I  *think* the problem is that `/img/pages/cs` only contains the (1) Section Book and (2) Add-on book. The main Scenario seems to be missing!

If you agree, I'll try to get jpg versions of the main Scenario book and then look over scenarios-cs.json to make any corrections. 

As an example, Scenario 3 points to /1/26 and /2/14. This _would_ be correct if it loaded Page 26 of the Scenario book and 14 of the Section. It instead loads 26 of the Section and 14 of the Add-On. I think the fastest is to **reorganize the folders** so that
/1/ = Main Scenario
/2/ = Sections
/3/ = Add-on.

| Page Reference | Current | Suggested |
|--------|--------|--------|
| /1/26 | Section 26 | Main 26 |
| /2/14 | Add-on 14 | Section 14 |

**Comment by jgwehr** [comment]
I think this can be closed
