### ISSUE TITLE
List individual requirements states for a scenario

### ISSUE THREAD

**Issue by tomasvanrijsse** [teamducro/gloomhaven-storyline#48]
It would be nice if the state of each individual requirement is shown on a scenario.

![image](https://user-images.githubusercontent.com/1403466/81652213-aaeb1f00-9433-11ea-8fb3-f3e069c7b58a.png)
Instead of that single red X I would prefer to see one green check and one red X

**Comment by dducro** [comment]
I like this feature.
How would you propose to show the OR requirements?
It should be very clear that in these cases if one of the two requirements is met the scenario is available.

**Comment by tomasvanrijsse** [comment]
Visualizing the actual requirement logic would be hard because you would have to add the current state and the outcome. 

Perhaps it's a good start to make them clickable and that each one opens the modal of the achievement.

**Comment by dducro** [comment]
You mean, keep one x / ✓ icon.
Just make the text in the requirement clickable if it has been unlocked?

**Comment by tomasvanrijsse** [comment]
Yes. 

![](https://user-images.githubusercontent.com/1403466/81652213-aaeb1f00-9433-11ea-8fb3-f3e069c7b58a.png)

In this case I'd expect the two achievement titles to be seperate links that open the individual achievement modals. 
Then we should also add the state of the achievement to the modal

**Comment by dducro** [comment]
Ok, sounds like a good solution.

**Comment by conerck** [comment]
Two suggestions:
Inline
![grafik](https://user-images.githubusercontent.com/3176260/82148413-5214ef80-9854-11ea-84ab-d600431447a7.png)

List style
![grafik](https://user-images.githubusercontent.com/3176260/82148437-71138180-9854-11ea-85b5-80cb189bea0f.png)

which do you guys prefer?

**Comment by conerck** [comment]
Side note: I don't think opening a modal with the achievements is particularly useful, since we only show the important information (e.g. which scenario the achievement is awarded from) once that particular scenario is complete.

E.g. in this case clicking on the missing The Power of Enhancement achievement would yield a modal like this 
![grafik](https://user-images.githubusercontent.com/3176260/82149335-fdbf3f00-9856-11ea-9865-5923d5b39d55.png)

I'm pretty much done implementing this. Will push it to a feature branch soon. Just going through all the scenario config to make sure it works.

**Comment by dducro** [comment]
Thanks, looking forward to the PR!
I think I prefer the first option, it better fits multiple screen sizes.

**Comment by tomasvanrijsse** [comment]
I like the list version more. I guess if we put "Requirements" on another line that it will fit most devices.

> Then we should also add the state of the achievement to the modal

I do think that the modal is sufficient once we add the state (achieved / not yet achieved)
And I'd also hide at what scenario it is achieved until it is actually achieved. Because that's also a guess when you play on the info from only the book.

**Comment by tomasvanrijsse** [comment]
But the way; why is one achievement red and the other white? Is the first one a link and the other isn't? Or does it try to tell if the achievement is achieved? Or does it say it doesn't match with the required state for this scenario?

Just making a point that I wouldn't use colors to convey meaning here.

**Comment by dducro** [comment]
@tomasvanrijsse Yes adding the achievement state in the modal is an option.
However, not indicating anything in this view is also annoying, because you have to click through to the achievement to see if it's awarded.
Something in red does indicate that something is incomplete, I think that's pretty clear to me.
I also do not prefer colored text, what would you propose?
A small x / ✔️(without a circle) in front of every line?

**Comment by conerck** [comment]
There should be some indication which condition is missing. That was the whole point of this issue, isn't?
I tried with strikethrough text as an alterantive, but that doesn't really look good, because the strikethrough on font isn't really centered and offset towards the top.

The red text was my suggestion for it, but I'm open for (x) / checkmark icons,but then I would vote for removing the (x) on the entire line, because otherwise it gets too cluttered.

I'm open for suggestions, but there needs to be some indication, and personally I would skip the achievement modal completely, because - as I said - it's not adding any useful information at the moment.

**Comment by tomasvanrijsse** [comment]
I like it with the "and" separator on a dedicated line. 

And I initiated this issue because I'd love to see the state of an achievement in a glance. But scenarios like these make it hard to communicate state. 
<img width="414" alt="Gloomhaven storyline" src="https://user-images.githubusercontent.com/1403466/82157095-b7caa100-987f-11ea-98a1-5e2510993a93.png">

I would use red for unmet conditions and green for the matching ones. In this case both should be green if the first is complete and the second is incomplete.

**Comment by conerck** [comment]
I tried that as well, and that looks very busy.
Leaving completed ones as white is better imo.

![grafik](https://user-images.githubusercontent.com/3176260/82159927-1a2c9d00-9892-11ea-8e0c-f848220672be.png)

**Comment by dducro** [comment]
Agree, it isn't Xmas 😂

**Comment by dducro** [comment]
Idea:
- Keep "Requirements:" on it's own line in all cases
- all texts gray
- For one requirement keep it as is, so icon in front of "Requirements:"
- multiple AND
  - if not all requirements are met: icon on each requirement line, the word "and" after the first line
  - if all or none requirements are met: one icon before "Requirements:"
- For multiple OR
  - if not all requirements are met: ✔️icon on each requirement line, the word "or" after the first line, don't show the x icon in this case.
  - if all or none requirements are met: one icon before "Requirements:"

This way you have different ways of displaying the information, but I think it should be clear and no colored text.
What do you think?

**Comment by conerck** [comment]
That's significantly more complicated then the current logic. Not sure if it's worth it tbh.

I pushed my changes to the achievements branch.
* Any partial requirement that is not fulfilled is shown in red. 
* Everything else is gray
* One icon indicating the complete state as before.
* If a scenario is completed, the text is always gray as to not cause confusion (e.g. scenario 3 has "The Merchant Flees INCOMPLETE" which can turn invalid at a later point in the campaign, but that has no impact on scenario 3 if you have already completed it).

**Comment by dducro** [comment]
Thanks! 😄

**Comment by dducro** [comment]
What do you think of:
![Screen Shot 2020-05-18 at 21 44 54 copy](https://user-images.githubusercontent.com/2156884/82253641-a5209c80-9951-11ea-8cdb-6a2547be2943.png)
- multiple requirements met
- multiple requirements not met
- one requirement met
- one requirement not met 
- AND case, one of multiple requirements not met
- OR case, one of multiple requirements not met

**Comment by dducro** [comment]
I removed the click on requirement, I think it's annoying, you can't navigate back easily and it doesn't add much value in my opinion.

**Comment by conerck** [comment]
looks good
