### ISSUE TITLE
Add choice dialog to 25/33

### ISSUE THREAD

**Issue by dducro** [teamducro/gloomhaven-storyline#63]
Thanks @conerck for 0b934619b154ee1b6925a479c5d55e1decefeeb4
A great way of implementing a dynamic dialog!

**Comment by dducro** [comment]
I don't think the dialog is triggered after completing the scenario.
With the dialog, it should only change the scenario state after a choice is made, so if the user cancels the choice nothing happend. This is the case with scenario 13.

**Comment by dducro** [comment]
Ah, I see, it keeps prompting if the choice isn't made because the show condition is still valid.
However if the user cancels, should it also prompt when opening 34?
What's your opinion?
I think I still prefer the same behaviour from 13.

**Comment by conerck** [comment]
Yea, I saw how you did it. The problem is that completing the scenario grants the achievement, which then triggers the condition.

You could change it and hook into the stateChange event and then check if the trigger condition would be met _if_ the statechange would go through, but I prefered the logic to trigger when a certain condition is eventually reached, instead of hooking into all the places from which the condition can be reached.

I also had one other thing in mind, where the prompt could be used, but I can't seem to remember what it was right now.

**Comment by dducro** [comment]
I think I'll implement a hybrid. What do you think of keeping the prompt logic the same.
In the scenario.vue when a prompt is available, on a change (e.g. completing/unlocking) log it temporarily within that component, then undo it when the prompt is canceled.

This way if the user cancels normally the scenario state is back to incomplete, and if the page is refreshed or something, it will still ask the user when opening the scenario again because of the show condition.

**Comment by conerck** [comment]
I'd be absolutely fine with that. It's not that I think my approach was better, just that I struggled to get the "undo" done with the multiple entry points. If you can find a way to make it work, I'm all for it.

**Comment by dducro** [comment]
@conerck An other question I was thinking about unlocking achievements via road/city events.
For some scenarios like 87/79 this is at the same time when the scenario is unlocked. So I could add something that gains the achievement when the state changes from hidden too incomplete.
However as stated in #59 an achievement can also be gained without any new scenarios.
Do you have any idea's on adding them manually without spoilers?

I'm thinking of a list of road/city event numbers that unlock achievements, so the user can choose from them, this will in turn unlock the achievement, on the achievement modal it should show the event card which gained it. I don't know if this covers all cases or if there are other means of gaining achievements.

**Comment by conerck** [comment]
Adding achievements on discovery was on my to-do list as well. I think that's the best approach.

For other achievements: I think there is only one (Ancient Tech) that can be gained from outside sources.

I'd probably opt for adding manual achievement management instead of doing it indirectly with event cards.
Just a (+) button on the achievement page that shows a minimal dialog with an autocomplete text box for the achievement name.

**Comment by dducro** [comment]
Agree with the (+) button and autocomplete, not via the event cards.
I just looked through the event cards and there are some party achievements missing from the json that are unlocked via event cards. Some unlock a scenario directly others don't.
