### ISSUE TITLE
Incorrect summary and preceding events for 22, 35, 36

### ISSUE THREAD

**Issue by ErikLevin** [teamducro/gloomhaven-storyline#81]
At [my save](https://gloomhaven-storyline.com/#/shared/1/local/N4RozgjARAXKYBcQGMA0IEG0oHYoF0BfdAQwHMBhAJVlBLGwHFqBZA4kE5qtuTgdxAR0yAPbCQAGxAAGDmAAWoZApKYh6CVs07Z6GfsN7jBk7tMz86AJYATYLmgw9uAEywXOAMweDuACy+qLgArEG4AGwewrh4zn44ABzhOACc4YkyGU4aUInu8cGJPoV5gaWJYRVRFXEuickV6aWpWS05fqkFLqklPeU9VbIcAA7W-ugAThHoAK7qFkaLZkJEpAAKAGIAyrQCGiji6NJy6GAF8EhoGNgReGvgJZco6FhQEWEPYOXP129eyWC-iiDxI6wAUus9iRBBIxBITvJGs9rPJmij5FVfq9sIFgq5kl8atiblAQlkvhA2iS3hBoJSfuArjioK4QfIIOimSBURsAIIAEQAotDYSIjlJhmdXE4MdKLty-tgZexSGQ+VQACrQhhQRgaqDBfUUVWcfU0Pgw4xiUzSCDyLyyxUsiLpL5eLHc3mPYlejhcTXrEWWsWHBFSs18k0hg7w44RsBeOKXKCTACmAEdZtZ07YoA7kX6zl4uYgefJ-E8i+BEk6y9YXYTMQqy8hMVXWyzHaawCFGZ3Sa5Pv71gKAEKi2MSxFnfJ7AdvCLuImFhfYLw+IiEIA), the summary of 22 as well as the "preceding events" log for 35 and 36 all read:

> You've retrieved the artifact, as the demon requested. It's abundantly clear that the artifact has been corrupted. If you bring this to the demon, he will most certainly use it for a great and terrible evil.
> You sealed the rift without handing over the artifact to the Demon. Clearly it was not to be trusted with such a dangerous and powerful item.

It sounds like the second paragraph should only be there if I've completed 19, which I haven't. And it sounds like only one of the paragraphs should be there.

Comparing with the Gloomhaven Quest Log scripted Google Sheet, it looks like, at this point, "[Dark Souls Stage 1](https://boardgamegeek.com/geeklist/237840/item/5999726#item5999726)" should be the Preceding Events for 35, [Dancing With the Devil, Stage 1](https://boardgamegeek.com/geeklist/237840/item/5999737#item5999737) for 36, and maybe [The Artifact, Stage 2](https://boardgamegeek.com/geeklist/237840/item/5999150#item5999150) should be the Summary of 22.

I'd love to submit a pull request fixing it, but figuring out how it should be means I'd have to read ahead in the quest log and spoil my game... I'll have to come back to it later in that case.

**Comment by conerck** [comment]
Hey @dducro,

this seems to be the result of a merge gone bad.

Back in May I merged the quests Dark Souls (28) and Dancing with the Devil (29) into one, because it really is just two different outcomes of the same quest. https://github.com/teamducro/gloomhaven-storyline/commit/f8dec7de886c32027118fe14f0de610a3ffadfb1
To accomadate that I did however add another stage to the quest (previously they both had 4 steps, the combined one had 5)

Then in https://github.com/teamducro/gloomhaven-storyline/commit/1f4da3f518d38028d01f85054ea84039f23d9b72 the previous state in en.js was restored, however the previous state of quest.json was not.

I'm not sure if the merge messed up anything else, but you should take a look at it.

**Comment by dducro** [comment]
Thanks! I'll check quests 28 and 29 and push a fix asap.

**Comment by dducro** [comment]
I restored the changes @conerck made to the Dark Souls quest.
I'll review the rest of the merge.
