### ISSUE TITLE
Missing unique items

### ISSUE THREAD

**Issue by elfosardo** [teamducro/gloomhaven-storyline#84]
In the Party Sheet there's no easy way to track unique items (items from 96 to 133, plus solo scenario items) unlocked in treasures or events.

**Comment by dducro** [comment]
True, I wasn't sure if people would want this, personally I don't use this with my party because we play one campaign.
The party sheet could be expanded to include the tracking of these items.
You mean that the user would be able to remake the item/event decks based on these lists right?

Unlocked treasures is tracked in the scenario list.
To see a list of scenarios with missed treasures you can use the "missed treasures" filter.

**Comment by elfosardo** [comment]
mainly the item decks based on which treasures have been opened, so I know that that specific treasure is available
I track that in my campaign

**Comment by IRQs** [comment]
Our party would appreciate such a functionality as well. We also play only one campaign but thanks to Covid-19, we have started to play remotely (with me streaming the "physical" game via webcams). At the moment, I manually have to maintain a list of available items for them to buy. And with all things manual, I often simply forget to keep that list accurate.

If the Gloomhaven Storyline would automatically update such a list based on completed scenarios (and events), that'd be a huge boost obviously. As a quick win, tracking unique items manually in the party sheet would already be great, since all the other items can already be tracked there.

**Comment by dducro** [comment]
I added items 96 - 150, storage of the party sheet was also slightly improved!

I did not add support for the items you unlock before their prosperity level.
This is because they're not added to the town store.
I do not have support for individual player sheets, in my understanding these should be recorded there.
